import type { WeaponDef, WeaponId, WeaponState, Loadout } from './types';

export const WEAPONS: Record<WeaponId, WeaponDef> = {
  ar: {
    id: 'ar',
    name: 'M4 CARBINE',
    short: 'AR',
    damage: 24,
    rof: 0.095,
    spread: 0.045,
    speed: 1500,
    mag: 30,
    reserve: 180,
    reload: 1.7,
    pellets: 1,
    range: 900,
    auto: true,
    recoil: 1.6,
    kick: 5,
    moveMult: 1,
    tracer: '#ffd27a',
    length: 30,
    width: 5,
    sound: 'ar',
    optimal: 380,
  },
  smg: {
    id: 'smg',
    name: 'MP5 VECTOR',
    short: 'SMG',
    damage: 16,
    rof: 0.058,
    spread: 0.085,
    speed: 1300,
    mag: 36,
    reserve: 216,
    reload: 1.45,
    pellets: 1,
    range: 620,
    auto: true,
    recoil: 1.2,
    kick: 4,
    moveMult: 1.12,
    tracer: '#ffe8a8',
    length: 22,
    width: 5,
    sound: 'smg',
    optimal: 240,
  },
  shotgun: {
    id: 'shotgun',
    name: 'SPAS-12',
    short: 'SG',
    damage: 13,
    rof: 0.78,
    spread: 0.2,
    speed: 1200,
    mag: 7,
    reserve: 42,
    reload: 2.4,
    pellets: 8,
    range: 330,
    auto: false,
    recoil: 5,
    kick: 10,
    moveMult: 1.05,
    tracer: '#ffb060',
    length: 32,
    width: 6,
    sound: 'shotgun',
    optimal: 150,
  },
  sniper: {
    id: 'sniper',
    name: 'AWM INTERVENTION',
    short: 'SNP',
    damage: 105,
    rof: 1.25,
    spread: 0.003,
    speed: 3000,
    mag: 5,
    reserve: 30,
    reload: 2.6,
    pellets: 1,
    range: 1800,
    auto: false,
    recoil: 7,
    kick: 12,
    moveMult: 0.9,
    tracer: '#9ad8ff',
    length: 42,
    width: 4,
    sound: 'sniper',
    optimal: 620,
  },
  lmg: {
    id: 'lmg',
    name: 'M249 SAW',
    short: 'LMG',
    damage: 21,
    rof: 0.085,
    spread: 0.075,
    speed: 1450,
    mag: 100,
    reserve: 200,
    reload: 3.6,
    pellets: 1,
    range: 950,
    auto: true,
    recoil: 2.2,
    kick: 6,
    moveMult: 0.85,
    tracer: '#ff9a5c',
    length: 36,
    width: 7,
    sound: 'lmg',
    optimal: 420,
  },
  pistol: {
    id: 'pistol',
    name: 'M1911',
    short: 'PST',
    damage: 30,
    rof: 0.17,
    spread: 0.03,
    speed: 1300,
    mag: 8,
    reserve: 64,
    reload: 1.2,
    pellets: 1,
    range: 600,
    auto: false,
    recoil: 1.4,
    kick: 6,
    moveMult: 1.15,
    tracer: '#fff1c9',
    length: 16,
    width: 4,
    sound: 'pistol',
    optimal: 260,
  },
};

export function makeWeapon(id: WeaponId): WeaponState {
  const def = WEAPONS[id];
  return { def, mag: def.mag, reserve: def.reserve };
}

export const LOADOUTS: Loadout[] = [
  {
    id: 'assault',
    name: 'ASSAULT',
    desc: 'Balanced M4 carbine. Reliable at any range.',
    primary: 'ar',
    secondary: 'pistol',
    grenades: 2,
    icon: '⚔',
  },
  {
    id: 'cqb',
    name: 'BREACHER',
    desc: 'SPAS-12 shotgun + MP5. Devastating up close.',
    primary: 'shotgun',
    secondary: 'smg',
    grenades: 3,
    icon: '💥',
  },
  {
    id: 'recon',
    name: 'RECON',
    desc: 'AWM sniper. One shot, one kill.',
    primary: 'sniper',
    secondary: 'pistol',
    grenades: 1,
    icon: '🎯',
  },
  {
    id: 'support',
    name: 'SUPPORT',
    desc: 'M249 SAW. 100-round belt of suppression.',
    primary: 'lmg',
    secondary: 'pistol',
    grenades: 2,
    icon: '🛡',
  },
  {
    id: 'runner',
    name: 'RUNNER',
    desc: 'MP5 Vector. Fast and furious.',
    primary: 'smg',
    secondary: 'pistol',
    grenades: 2,
    icon: '⚡',
  },
];

export const BOT_PRIMARIES: WeaponId[] = ['ar', 'ar', 'smg', 'shotgun', 'sniper', 'lmg', 'ar', 'smg'];
